# libraries

import os
from snakemake.utils import min_version

min_version("6.4.1")


wildcard_constraints:
    sample="[a-zA-Z\d]+",
    sra="SRR[\d]+"




##### setup report #####
configfile: "config/config.yaml"

##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://condaforge/mambaforge:22.11.1-4"

report: "report/workflow.rst"

include: "rules/common.smk"
include: "rules/fetchfastq.smk"
include: "rules/fastqc.smk"
# include: "rules/align.smk"
# include: "rules/annotate.smk"
# include: "rules/generatematrix.smk"
# include: "rules/diffexp_deseq2.smk"
# include: "rules/wgcna.smk"
# include: "rules/enrichment_genekitr.smk"
# include: "rules/hamr.smk"
# include: "rules/modtect.smk"
# include: "rules/ref.smk"
# include: "rules/vis_volcano.smk"
# include: "rules/vis_pcaplot.smk"

##### target rules #####


rule all:
    input:
        get_final_output()
