# libraries

import os
from snakemake.utils import min_version

min_version("6.4.1")


wildcard_constraints:
    sample="[a-zA-Z0-9]+",
    accession="SRR[0-9]+",


##### setup report #####
configfile: "config/config.yaml"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://condaforge/mambaforge:22.11.1-4"


report: "report/workflow.rst"


include: "rules/common.smk"
# preprocessing
include: "rules/preprocessing/fetchfastq.smk"
include: "rules/preprocessing/align.smk"
include: "rules/preprocessing/quantification.smk"
# include: "rules/preprocessing/expression.smk"
include: "rules/preprocessing/assembly.smk"
# include: "rules/preprocessing/transcript_splicing.smk"
include: "rules/preprocessing/transcriptome_compare.smk"
# include: "rules/preprocessing/expression.smk"
# include: "rules/preprocessing/bam_process.smk"
include: "rules/preprocessing/ref.smk"
# include: "rules/preprocessing/modification.smk"
# analysis
# include: "rules/analysis/deg/deseq2.smk"
# include: "rules/analysis/deg/edger.smk"
# include: "rules/analysis/deg/limma.smk"
# include: "rules/analysis/enrichment.smk"
# include: "rules/analysis/dark_channel_biomarker.smk"
# visualization
# include: "rules/visualization/vis.smk"
# include: "rules/visualization/deg_visualization.smk"
# qc
include: "rules/qc/qc.smk"
include: "rules/qc/bamqc.smk"
include: "rules/qc/fastqc.smk"


# include: "rules/vis_pcaplot.smk"

##### target rules #####


rule all:
    input:
        get_final_output(),
