rule fastp_fastqc:
    input:
        fq1=,
        fq2=,
    output:
        fq1=
        fq2=
        qc_html=,
        qc_json=,
    log:
        ""
    benchmark:
        ""
    params:
        extra=""
    conda:
        "../envs/fastp.yaml"
    threads:
        config['threads']["fastp"]
    shell:
        "fastp"