rule count_matrix:
    input:
        expand(
            "results/star/{sample.sample_name}/ReadsPerGene.out.tab",
            sample=samples.itertuples(),
        ),
    output:
        "results/counts/count_matrix.tsv",
        "results/counts/count_matrix_unstrandedness.tsv",
        "results/counts/count_matrix_strandedness.tsv",
        "results/counts/count_matrix_reverse.tsv",
        "results/counts/strandedness_check.pdf"
    log:
        "logs/count-matrix.log",
    params:
        samples=samples["sample_name"].tolist(),
    conda:
        "../envs/pandas.yaml"
    script:
        "../scripts/count-matrix.py"