samples: config/samples.tsv

threads:
  sra: 6
  fastp: 6
  star: 6
  hisat2: 6


fastp:
  se_extra: ''
  pe_extra: ''

star:
  extra: ''

hisat2:
  extra: ''

ref:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 104
  # Genome build
  build: GRCh38

reference:
  select_contigs:
    - 22