samples: config/samples.tsv

params:
  sratools_fetchfastq: "--gzip --split-3 "
  fastp: "-c "
  star: ""
  featurecounts: " -O --fracOverlap 0.2 -J −−extraAttributes  gene_name,gene_type "
threads:
  fastp: 12
  star: 12
  deseq2: 12

thresholds:
  deseq2:
    count: 10
    log2foldchange: 1
    padj: 0.05
  volcano:
    log2foldchange: 1
    padj: 0.05




ref:
  # Ensembl species name
  species: saccharomyces_cerevisiae
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 100
  # Genome build
  build: R64-1-1
  go_name: yeast
  kegg_name: sce

diffexp:
  # contrasts for the deseq2 results method
  subclass: time_label
  contrasts:
    KFC1-vs-WT:
      - KFC1
      - WT
  model: ~condition

vis:
  pcatools:
    color_by: condition
    shape_by: time_label