$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string

  ref:
    type: object
    properties:
      species:
        type: string
      release:
        type: integer
      build:
        type: string
    required:
      - species
      - release
      - build


  threads:
    type: object
    properties:
      fastp:
        type: integer
      star:
        type: integer
      deseq2:
        type: integer


  params:
    type: object
    properties:
      sratools_fetchfastq:
        type: string
      fastp:
        type: string
      star:
        type: string
    required:
      - star

required:
  - samples
  - ref
  - params
  - threads

