name: Tests

on:
  push:
    branches: [ main, dev]
  pull_request:
    branches: [ main ]


jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing:
      runs-on: ubuntu-latest
      needs: 
        - Linting
        - Formatting
      steps:
      - uses: actions/checkout@v3
      - name: Test workflow
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .test
          snakefile: workflow/Snakefile
          args: "--use-conda --show-failed-logs --cores 3 --conda-cleanup-pkgs cache "
      - name: Check all files
        run: |
          ls -lthrR .test/
      - name: Test report
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .test
          snakefile: workflow/Snakefile
          args: "--report report.zip"


  Testing2:
    runs-on: ubuntu-latest
    needs:
      - Linting
      - Formatting
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda install -c conda-forge mamba
      - name: Setup snakemake
        run: |
          mamba install -c conda-forge -c bioconda snakemake singularity snakefmt
          conda clean --all -f
      - name: Test workflow
        run: |
          snakemake --directory .test --use-conda --show-failed-logs --cores 1 --conda-cleanup-pkgs cache --use-singularity
      - name: Check all files
        run: |
          ls -lthrR .test
  